---
title: "Marketing Report"
subtitle: "Office of Marketing and Brand Management"
date: "`r Sys.Date()`"

output:
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_html: default
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: tinytex
bibliography: skeleton.bib
link-citations: yes
---

```{r setup, include=FALSE}
library(tufte)
library(knitr)
library(formatR)
library(blastula)
library(gt)
library(glue)
library(formattable)
library(hms)
library(tidyverse)
library(knitr)
library(ggpubr)


# invalidate cache when the tufte version changes
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	cache.extra = packageVersion("tufte"),
	tidy = FALSE
)
options(tinytex.verbose = TRUE)
```

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

# __FY21 Analytics Project Template__

# Description


`r newthought('This script segments')` the 1S21 data.




# Findings


__Margin Figures__

Images and graphics play an integral role in Tufte's work. To place figures in the margin you can use the 

```{r fig-margin, fig.margin = TRUE, fig.cap = "MPG vs horsepower, colored by transmission.", fig.width=3.5, fig.height=3.5, cache=TRUE, message=FALSE}
colors <-  c("#F6A704", "#0E1033","#4E7B14","#A92007","#D47E0A")
mtcars2 <- mtcars
mtcars2$am <- factor(
  mtcars$am, labels = c('automatic', 'manual')
)
a_a <- ggplot(mtcars2, aes(hp, mpg, color = am)) +
  geom_point() + geom_smooth(se=FALSE ) +
  theme(legend.position = 'bottom') + theme_bw() +
    scale_color_manual(
        values=colors)
a_a
```




```{r eval=FALSE, include=FALSE}
imgur_image <-
   add_imgur_image(
     image = a_a,
     client_id = "851117406f0b457"
   )

```

#

__Save an Image to Email & Compose and Send an Email__

The plot to the side will be included in an email. 

```{r eval=FALSE, include=FALSE}


body_text <-
  glue(
    "


The data he sent makes much more sense. \\
It was excluding students who are not yet captured \\
because the census report is a couple months away. We \\
discussed criteria for a new list which will hopefully \\ 
include students who have deposited and are due to start \\
in the upcoming months. This will give us a second year \\
of applications so we can look at the patterns of ap-\\
plication flow. He's sending the list by EOD tomorrow.



{imgur_image}


Thank you,

Christine Iyer \\
Marketing Data Analyst \\
University of Southern Maine
"
  ) %>% md()

compose_email(body = body_text) %>%
  smtp_send(
    #to = "wrike+into523544264@wrike.com",
    to = "edithbird5@gmail.com",
    #cc = "tracy.st@maine.edu",
    from = "christine.iyer@maine.edu",
    subject = "Project Update",
    credentials = creds_key(id = "gmail")
  )
```


```{r}
Leads <- read.csv("C:/Users/christine.iyer/Box/FY21 Search/Search 1/UploadedLeadsInSF/1S21_AllLeads.csv", header = T, stringsAsFactors = F)



```

```{r}
library(dplyr)
LeadsCode <- Leads %>% mutate(Code = paste0(Lead.Segment.Cappex, "*", Lead.Segment.College.Board, "*", Lead.Segment.Niche, "*", Lead.Segment.NRCCUA))



LC <- LeadsCode[1:200, c(4, 28)]
LC <- LC %>% 
  mutate(NewCode = ifelse(nchar(as.character(Code)) < 18,Code,  "Multiple Vendors"), 
         NewCode = gsub('\\*', "", NewCode))

head(LC, 200)
```

* 

*

\href{https://www.wrike.com/open.htm?id=525346252}{{\color{blue}{\underline{Wrike Project Details}}}}

\href{https://github.com/edithbird/fy20_cybersecurity}{{\color{blue}{\underline{Github Repository}}}}

```{marginfigure, echo = TRUE}
Notice that there is no number preceding the note. $x \in [a, b]$有
$$\frac{d}{dx}\left( \int_{a}^{x} f(u)\,du\right)=f(x).$$
```





```{r bib, include=FALSE}
# create a bib file for the R packages used in this document
knitr::write_bib(c('base', 'rmarkdown'), file = 'skeleton.bib')
```
